services:
  dist-test-run:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - CODEXDOCKERIMAGE=thatbenbierens/nim-codex:dhting
      - BRANCH="feature/docker-image-testruns"
      - KUBECONFIG=/opt/kubeconfig
      - LOGPATH=/opt/logs
      - RUNNERLOCATION=ExternalToCluster
