services:
  codex-node1:
    # image: codexstorage/nim-codex:sha-82b0399
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - BRANCH="feature/docker-image-testruns"
      - KUBECONFIG=kubeconfigplease
      - LOGPATH="/"
      - RUNNERLOCATION="ExternalToCluster"
    ports:
      - 8080:8080/tcp # REST API
