services:
  codex-node1:
    # image: codexstorage/nim-codex:sha-82b0399
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - CODEX_LOG_LEVEL=${CODEX_LOG_LEVEL:-TRACE}
      - CODEX_METRICS=${CODEX_METRICS:-false}
    ports:
      - 8080:8080/tcp # REST API
